name: Generate Governance Index

on:
  push:
    paths:
      - 'Governance/**/*.md'
  workflow_dispatch:

jobs:
  build-index:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install PyYAML
        run: pip install pyyaml

      - name: Generate index.md
        run: |
          import os
          import yaml

          governance_dir = 'Governance'
          index_path = os.path.join(governance_dir, 'index.md')
          entries = []

          for root, _, files in os.walk(governance_dir):
              for file in files:
                  if file.endswith('.md') and file != 'index.md':
                      path = os.path.join(root, file)
                      with open(path, 'r', encoding='utf-8') as f:
                          lines = f.readlines()
                          if lines[0].strip() == '---':
                              front_matter = []
                              for line in lines[1:]:
                                  if line.strip() == '---':
                                      break
                                  front_matter.append(line)
                              metadata = yaml.safe_load(''.join(front_matter))
                              title = metadata.get('title', file)
                              rel_path = os.path.relpath(path, governance_dir)
                              entries.append(f"- [{title}]({rel_path})")

          with open(index_path, 'w', encoding='utf-8') as f:
              f.write("# Governance Index\n\n")
              f.write("\n".join(sorted(entries)))

        shell: python